### ISSUE TITLE
Send Data Format: str to json

### ISSUE THREAD

**Issue by BBSSJJ** [Gaebobman/CarbonCheck_homeserver#1]
현재 update_data_and_send.py 파일에서
def send_data_to_server(rows, ws) 함수가 서버로 데이터를 보내는 함수인데
```message = str(rows)``` 이 방식으로 메세지를 생성하면 문자열로 생성된 후 보내집니다. 
```message = json.dumps(rows)```  이런 방식으로 바꿔서 json형태로 보내주시기 바랍니다.

**Comment by Gaebobman** [comment]
ad166400ce8a72cb416b52985f306834726b8954 에서 반영 완료
